sonar.projectKey=nestjs-boilerplate
sonar.qualitygate.wait=true

sonar.qualitygate.timeout=600
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions= \
    **/*.entity.ts, \
    **/*.dto.ts

sonar.sources=src
sonar.coverage.exclusions= \
    commitlint.config.js, \
    node_modules, \
    **/shared/validators/**, \
    **/shared/pipes/**, \
    **/**/mikro-orm.config.ts, \
    **/config/*, \
    **/main.ts, \
    **/*.module.ts, \
    **/**/*.module.ts, \
    **/app.module.ts, \
    **/app.controller.spec.ts, \
    **/database/migration/db-migration.module.ts, \
    **/database/seeders/db-seeder.module.ts, \
    **/logging.module.ts, \
    **/query.util.ts, \
    **/dtos/*.dto.ts, \
    **/dto/*.dto.ts, \
    **/dto/*, \
    dto/*, \
    **/*.query.ts, \
    **/*.model.ts, \
    **/*.config.ts, \
    **/*.filter.ts, \
    **/*.main.ts, \
    **/*.logging.ts, \
    **/*.util.ts, \
    **/*.dto.ts, \
    **/**/*.dto.ts, \
    **/*.enum.ts, \
    **/**/*.enum.ts, \
    **/enums/*.enum.ts, \
    **/enum/*.enum.ts, \
    **/*.entity.ts, \
    **/**/*.entity.ts, \
    **/*.interface.ts, \
    **/**/*.interface.ts, \
    **/*.decorator.ts, \
    **/entities/**, \
    **/logging/*, \
    **/migrations/*, \
    **/seeders/*, \
    **/seeders/seed/*, \
    **/*.seeder.ts, \
    **/app.controller.ts, \
    **/app.service.ts, \
    **/env.validation.ts, \
    **/custom-throttler.guard.ts, \
    **/cli/**, \
    **/*.embeddable.ts, \
    **/index.ts, \
    **/*.spec.ts
